import { KnowledgeAbility } from './knowledge'
import { DocumentAbility } from './document'
export * from './user'
export * from './auth'
export * from './knowledge'
export * from './response'
export * from './document'
export * from './common'
export * from './dashboard'
export * from './team'
export * from './space'
export * from './collaborator'
export * from './notification'
export * from './search'
export * from './resourceAccess'
export * from './buildRoute'
// 能力类型（联合）
export type Ability = KnowledgeAbility | DocumentAbility
